# Numpy
-----
## 03. 배열 연산과 함수
### 텍스트 파일 다루기
- savetxt : 배열을 텍스트 파일로 저장
- loadtxt : 텍스트 파일을 배열로 불러오기

In [1]:
import numpy as np

data = np.random.rand(5, 3)
print(data)

# 텍스트  파일로 저장 
# np.savetxt('data.txt', data)    # 공백으로 구분
np.savetxt('data.txt', data, delimiter=",")    # ,로 구분(CSV)
# 텍스트 파일을 배열로 불러오기
# load_data = np.loadtxt('data.txt')
load_data = np.loadtxt('data.txt', delimiter=",")
print(load_data)

[[0.26052489 0.80359451 0.5358729 ]
 [0.29985426 0.22357166 0.92468143]
 [0.3627721  0.83637309 0.10576974]
 [0.02786072 0.893479   0.48074938]
 [0.35727255 0.66496871 0.36292983]]
[[0.26052489 0.80359451 0.5358729 ]
 [0.29985426 0.22357166 0.92468143]
 [0.3627721  0.83637309 0.10576974]
 [0.02786072 0.893479   0.48074938]
 [0.35727255 0.66496871 0.36292983]]
[[0.26052489 0.80359451 0.5358729 ]
 [0.29985426 0.22357166 0.92468143]
 [0.3627721  0.83637309 0.10576974]
 [0.02786072 0.893479   0.48074938]
 [0.35727255 0.66496871 0.36292983]]
[[0.26052489 0.80359451 0.5358729 ]
 [0.29985426 0.22357166 0.92468143]
 [0.3627721  0.83637309 0.10576974]
 [0.02786072 0.893479   0.48074938]
 [0.35727255 0.66496871 0.36292983]]


### 바이너리 파일 다루기
- save : 배열을 바이너리 파일로 저장
    - 넘파이 배열의 확장자는 .npy
- load : 바이너리 파일을 배열로 불러오기

※ 바이너리 형식으로 데이터를 저장하고 불러오면 데이터 손실 없이 빠르게 처리할 수 있으므로, 크기가 크고 복잡한 데이터를 다룰 때 특히 유용

In [2]:
import numpy as np
import os
# 가상의 데이터 생성
data = np.random.rand(5, 3)
print("data :\n", data)
# 데이터를 바이너리 형식으로 저장
if not os.path.exists('../generated'):
    os.makedirs('../generated')
np.save('../generated/data', data)

load_data = np.load('../generated/data.npy')
print("load_data :\n", load_data)

data :
 [[0.25819695 0.42524183 0.97628727]
 [0.62102506 0.7793474  0.55104562]
 [0.94919831 0.76385516 0.32681866]
 [0.98082864 0.36430706 0.63632237]
 [0.52619447 0.40259242 0.29286816]]
load_data :
 [[0.25819695 0.42524183 0.97628727]
 [0.62102506 0.7793474  0.55104562]
 [0.94919831 0.76385516 0.32681866]
 [0.98082864 0.36430706 0.63632237]
 [0.52619447 0.40259242 0.29286816]]
data :
 [[0.25819695 0.42524183 0.97628727]
 [0.62102506 0.7793474  0.55104562]
 [0.94919831 0.76385516 0.32681866]
 [0.98082864 0.36430706 0.63632237]
 [0.52619447 0.40259242 0.29286816]]
load_data :
 [[0.25819695 0.42524183 0.97628727]
 [0.62102506 0.7793474  0.55104562]
 [0.94919831 0.76385516 0.32681866]
 [0.98082864 0.36430706 0.63632237]
 [0.52619447 0.40259242 0.29286816]]
